"""Minimum Reporting Checklist generator.

Operationalizes the checklist proposed in "Building Fast, Evaluating Slow"
(arXiv:2607.19386) and generalizes it beyond autointerp: every field below
is a documented source of result variance in the 2025–2026 stability
literature. ``stresskit report`` renders the checklist as markdown for a
paper appendix; unanswered fields are flagged, not hidden.
"""

from __future__ import annotations

from typing import Dict, List, Optional, Tuple

# (key, title, why it matters)
CHECKLIST_FIELDS: List[Tuple[str, str, str]] = [
    ("model", "Model", "name + revision/hash of the subject model"),
    ("task", "Task / behavior", "the behavior the finding explains"),
    ("method", "Discovery method", "algorithm + implementation + version"),
    ("dataset", "Dataset / corpus", "name, size, and domain of the probing data"),
    ("sampling", "Example sampling", "how activating/contrast examples were selected"),
    ("n_seeds", "Seeds", "number of independent seeds (1 seed = a limitation)"),
    ("n_bootstrap", "Bootstrap draws", "number of dataset resamples, if any"),
    ("templates", "Prompt templates", "templates/paraphrases evaluated, or 'single template'"),
    ("hyperparams", "Hyperparameters swept", "thresholds, ablation type, corruption, metric, ..."),
    ("metric", "Evaluation metric", "faithfulness/score definition, exactly"),
    ("explainer", "Explainer/scorer models", "for autointerp pipelines: model names + versions"),
    ("stability", "Stability metrics", "Jaccard / flip rate / CV reported (attach a Stability Card)"),
    ("card", "Stability Card", "path or URL of the machine-readable card"),
]

_MISSING = "**NOT REPORTED** ⚠️"


def generate_checklist(answers: Optional[Dict[str, str]] = None) -> str:
    """Render the Minimum Reporting Checklist as markdown."""
    answers = answers or {}
    lines = [
        "# StressKit Minimum Reporting Checklist",
        "",
        "Fields marked *NOT REPORTED* are documented sources of result variance",
        "(arXiv:2607.19386, arXiv:2510.00845, arXiv:2608.13754).",
        "",
        "| field | value | why it matters |",
        "|---|---|---|",
    ]
    for key, title, why in CHECKLIST_FIELDS:
        value = answers.get(key, "").strip() if answers.get(key) else ""
        lines.append(f"| {title} | {value or _MISSING} | {why} |")
    n_missing = sum(1 for key, _, _ in CHECKLIST_FIELDS if not answers.get(key))
    lines.append("")
    if n_missing == 0:
        lines.append("✅ **All fields reported.**")
    else:
        lines.append(f"⚠️ **{n_missing}/{len(CHECKLIST_FIELDS)} fields not reported.**")
    lines.append("")
    lines.append("*Generated by [StressKit](https://github.com/Arth-Singh/Stresskit).*")
    return "\n".join(lines)


def missing_fields(answers: Dict[str, str]) -> List[str]:
    return [key for key, _, _ in CHECKLIST_FIELDS if not answers.get(key)]
