"""One-call stability battery for SAELens SAEs.

    from stresskit.adapters import sae_lens

    report = sae_lens.stability([sae_seed0, sae_seed1, sae_seed2])
    print(report.to_markdown())
    report.save("sae_stability.json")

Accepts SAELens ``SAE`` objects, torch tensors, or numpy arrays — anything
carrying a ``(n_features, d_model)`` decoder as ``.W_dec`` or being one.
Never imports sae_lens or torch itself.

Checks (graded A–D like every StressKit battery):

- **seed consistency** — mean pairwise MCC under optimal feature matching
  across the supplied SAEs. Default bar 0.7: SAEs retrained on the same
  data share roughly two-thirds of their features (arXiv:2501.16615), so
  falling well below that means the release's features are substantially
  seed artifacts. Needs >= 2 SAEs.
- **redundancy** — worst-case fraction of features that are near-duplicates
  of another feature (|cos| >= threshold) within any single SAE.
- **above noise floor** — cross-seed MCC rescaled against the MCC with a
  random Gaussian decoder of the same shape (the noise floor of optimal
  matching, which grows with n_features/d_model). Frozen random decoders
  match trained SAEs on several standard evals (arXiv:2602.14111); a
  release covering less than half the noise-to-perfect gap has no stable
  feature identity to report.
"""

from __future__ import annotations

import datetime as _dt
import json
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Sequence

import numpy as np

from . import sae as _sae
from ..battery import grade_checks
from ..card import _GRADE_COLORS, _GRADE_EMOJI, _fmt


def _wdec(obj: Any, max_features: Optional[int], seed: int) -> np.ndarray:
    W = getattr(obj, "W_dec", obj)
    if hasattr(W, "detach"):                      # torch tensor, no torch import
        W = W.detach().cpu().float().numpy()
    W = np.asarray(W, dtype=np.float32)
    if W.ndim != 2:
        raise ValueError(
            f"expected a (n_features, d_model) decoder, got shape {W.shape}"
        )
    if max_features is not None and W.shape[0] > max_features:
        rng = np.random.default_rng(seed)
        idx = np.sort(rng.choice(W.shape[0], size=max_features, replace=False))
        W = W[idx]
    return W


@dataclass
class SAEStabilityReport:
    name: str
    metrics: Dict[str, Any]
    checks: Dict[str, Any]
    grade: str
    notes: List[str] = field(default_factory=list)
    created_at: str = ""

    def to_dict(self) -> Dict[str, Any]:
        from .. import __version__

        return {
            "artifact": "stresskit_sae_stability_report",
            "schema_version": "0.1",
            "stresskit_version": __version__,
            "created_at": self.created_at,
            "name": self.name,
            "metrics": self.metrics,
            "checks": self.checks,
            "verdict": {"grade": self.grade},
            "notes": self.notes,
        }

    def save(self, path: str) -> None:
        with open(path, "w", encoding="utf-8") as f:
            json.dump(self.to_dict(), f, indent=2, default=str)
            f.write("\n")

    def badge_dict(self) -> Dict[str, Any]:
        mcc = self.metrics.get("mean_mcc")
        detail = f"MCC={mcc:.2f}" if mcc is not None else \
            f"redundant={self.metrics.get('max_redundant_fraction', 0):.1%}"
        return {
            "schemaVersion": 1,
            "label": "SAE stability",
            "message": f"{self.grade} · {detail}",
            "color": _GRADE_COLORS.get(self.grade, "lightgrey"),
        }

    def to_markdown(self) -> str:
        emoji = _GRADE_EMOJI.get(self.grade, "")
        lines = [
            f"# {emoji} SAE Stability Report — grade **{self.grade}**",
            "",
            f"> {self.name} · {self.metrics.get('n_saes')} SAE(s), "
            f"{self.metrics.get('n_features')} features × "
            f"{self.metrics.get('d_model')} dims",
            "",
            "| check | value | threshold | pass |",
            "|---|---|---|---|",
        ]
        for name, c in self.checks.items():
            op = "≤" if c.get("op") == "<=" else "≥"
            lines.append(
                f"| {name.replace('_', ' ')} | {_fmt(c.get('value'))} | "
                f"{op} {_fmt(c.get('threshold'))} | "
                f"{'✅' if c.get('passed') else '❌'} |"
            )
        if self.notes:
            lines += ["", "## Notes", ""] + [f"- {n}" for n in self.notes]
        lines += ["", "*Generated by [StressKit](https://github.com/Arth-Singh/Stresskit).*"]
        return "\n".join(lines)


def stability(
    saes: Any,
    *,
    redundancy_threshold: float = 0.9,
    mcc_bar: float = 0.7,
    redundancy_bar: float = 0.05,
    noise_excess_bar: float = 0.5,
    max_features: Optional[int] = None,
    seed: int = 0,
    name: str = "sae",
) -> SAEStabilityReport:
    """One call, graded stability report for an SAE release.

    ``saes``: one SAE or a sequence of SAEs trained with different seeds
    on the same data. Feature matching is O(n_features²) in memory — for
    very wide SAEs pass ``max_features`` to audit a deterministic random
    subsample (noted on the report).
    """
    if not isinstance(saes, (list, tuple)):
        saes = [saes]
    if not saes:
        raise ValueError("no SAEs given")
    decoders = [_wdec(s, max_features, seed) for s in saes]
    shapes = {W.shape for W in decoders}
    if len({W.shape[1] for W in decoders}) > 1:
        raise ValueError(f"SAEs disagree on d_model: {sorted(shapes)}")

    notes: List[str] = []
    if max_features is not None:
        notes.append(
            f"audited a deterministic subsample of {max_features} features per SAE"
        )

    metrics: Dict[str, Any] = {
        "n_saes": len(decoders),
        "n_features": int(decoders[0].shape[0]),
        "d_model": int(decoders[0].shape[1]),
    }
    checks: Dict[str, Any] = {}

    # redundancy: worst case over the supplied SAEs
    audits = [
        _sae.redundancy_audit(W, threshold=redundancy_threshold) for W in decoders
    ]
    worst = max(a["redundant_fraction"] for a in audits)
    metrics["max_redundant_fraction"] = worst
    metrics["redundancy_per_sae"] = [
        {k: a[k] for k in ("n_redundant_features", "redundant_fraction", "n_clusters")}
        for a in audits
    ]
    checks["redundancy"] = {
        "value": worst,
        "threshold": redundancy_bar,
        "op": "<=",
        "passed": worst <= redundancy_bar,
        "description": f"worst-case near-duplicate feature fraction (|cos| ≥ {redundancy_threshold})",
    }

    if len(decoders) >= 2:
        consistency = _sae.seed_consistency(decoders)
        metrics["mean_mcc"] = consistency["mean_mcc"]
        metrics["min_mcc"] = consistency["min_mcc"]
        metrics["pairwise_mcc"] = consistency["pairwise_mcc"]
        checks["seed_consistency"] = {
            "value": consistency["mean_mcc"],
            "threshold": mcc_bar,
            "op": ">=",
            "passed": consistency["mean_mcc"] >= mcc_bar,
            "description": "mean pairwise MCC across seeds (optimal feature matching)",
        }

        # Noise floor: MCC against a random Gaussian decoder of the same
        # shape. The floor is NOT near zero — optimal matching of n random
        # features in d dims finds spurious partners, and the floor grows
        # with n/d — so a raw ratio is regime-dependent. The scale-free
        # statistic is the excess over the floor: what fraction of the
        # noise-to-perfect gap does cross-seed agreement actually cover?
        rng = np.random.default_rng(seed ^ 0xDEAD)
        rand_mccs = []
        for W in decoders:
            R = rng.standard_normal(W.shape).astype(np.float32)
            rand_mccs.append(_sae.match_features(W, R)["mcc"])
        noise_floor = float(np.mean(rand_mccs))
        metrics["random_decoder_mcc"] = noise_floor
        gap = max(1e-9, 1.0 - noise_floor)
        excess = (consistency["mean_mcc"] - noise_floor) / gap
        metrics["mcc_excess_over_noise"] = excess
        checks["above_noise_floor"] = {
            "value": excess,
            "threshold": noise_excess_bar,
            "op": ">=",
            "passed": excess >= noise_excess_bar,
            "description": "(cross-seed MCC − random-decoder MCC) / (1 − random-decoder MCC)",
        }
        grade = grade_checks(checks, rule="v0.3")
    else:
        notes.append(
            "single SAE supplied — seed consistency and the noise-floor "
            "margin need ≥ 2 seeds; only redundancy was checked, so the "
            "grade is capped at C. Retrain with one more seed before "
            "claiming feature identity."
        )
        # a battery that could not test feature identity must not read as
        # a certification, however clean the redundancy number is
        grade = grade_checks(checks, rule="v0.3")
        if grade in ("A", "B"):
            grade = "C"

    return SAEStabilityReport(
        name=name,
        metrics=metrics,
        checks=checks,
        grade=grade,
        notes=notes,
        created_at=_dt.datetime.now(_dt.timezone.utc).isoformat(timespec="seconds"),
    )
